### ISSUE TITLE
[Front] CSS poprawki

### ISSUE THREAD

**Issue by majcheradam** [majcheradam/school-challenge-03#3]
Tutaj oryginał bez sówaka:
![image](https://user-images.githubusercontent.com/63547690/214632874-3545e7c2-1ca1-453a-a032-afb1f0cd6456.png)

A tutaj twoja wersja z sówakiem:
![image](https://user-images.githubusercontent.com/63547690/214632990-ed920d5d-89ba-4333-bdf8-ce701d47f58f.png)

- Pokombinuj aby strona zawsze miała na desktopie i tablecie wysokość `100vh`, co zlikwiduje suwak
- Spraw aby `main-conteiner` na desktopie miał wysokość taką jak w oryginale **nie ustawiając tej wartości na sztywno**
- Spraw aby 'footer' na desktopie miał wysokość taką jak w oryginale **nie ustawiając tej wartości na sztywno**

**Comment by majcheradam** [comment]
Poprawki masz w komentarzach ostatniego commita ;)

W razie pytań możesz śmiało pisać/dzwonić! :D

**Comment by majcheradam** [comment]
Ponieważ u mnie jest dalej pasek ;)

![image](https://user-images.githubusercontent.com/63547690/215285748-c1f2c7a7-e4e4-46b5-8949-eb913acf8f85.png)

**Comment by Domun335** [comment]
Powinno śmigać z tym paskiem, w sensie bez paska xD

**Comment by majcheradam** [comment]
Działa 👍🏻
